# Generated by Django 4.2.21 on 2026-02-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('h_win', models.FloatField()),
                ('draw', models.FloatField()),
                ('a_win', models.FloatField()),
                ('pred_ftr', models.CharField(max_length=1)),
                ('pred_fthg', models.FloatField()),
                ('pred_ftag', models.FloatField()),
                ('max_value', models.FloatField()),
                ('max_value_result', models.CharField(max_length=20)),
                ('actual_ftr', models.CharField(blank=True, max_length=1, null=True)),
                ('actual_fthg', models.IntegerField(blank=True, null=True)),
                ('actual_ftag', models.IntegerField(blank=True, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['div'], name='home_predic_div_57f16e_idx'), models.Index(fields=['resolved'], name='home_predic_resolve_3c3ef7_idx'), models.Index(fields=['date'], name='home_predic_date_f7d715_idx')],
                'unique_together': {('div', 'date', 'home_team', 'away_team')},
            },
        ),
    ]
