# Generated by Django 4.2.21 on 2026-02-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_prediction_odds_a_prediction_odds_d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='btts_no',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prediction',
            name='btts_yes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prediction',
            name='over25',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prediction',
            name='over25_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='under25',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prediction',
            name='under25_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
