# Generated by Django 4.2.21 on 2026-02-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_add_btts_over_under_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='best_odds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='odds_over25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='odds_under25',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
